apiVersion: v2
name: artsy
description: A Helm chart for deploying the Artsy mobile app backend
type: application
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.4