apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artsy.fullname" . }}-config
  labels:
    {{- include "artsy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }} # Use .Release.Namespace for the deployed namespace
data:
  # PostgreSQL Connection (non-sensitive parts)
  Database__Host: {{ .Values.postgresql.host | quote }}
  Database__Port: {{ .Values.postgresql.port | default "5432" | quote }}
  Database__Name: {{ .Values.postgresql.database | quote }}

  Jwt__Issuer: {{ .Values.jwt.issuer | quote }}
  Jwt__Audience: {{ .Values.jwt.audience | quote }}
  Jwt__DurationInMinutes: {{ .Values.jwt.durationInMinutes | default "1" | quote }}
  Jwt__RefreshTokenTTLDays: {{ .Values.jwt.refreshTokenTTLDays | default "7" | quote }}

  CookieSettings__Secure: {{ .Values.cookieSettings.secure | default "true" | quote }}
  CookieSettings__SameSiteAccessToken: {{ .Values.cookieSettings.sameSiteAccessToken | default "Lax" | quote }}
  CookieSettings__PathAccessToken: {{ .Values.cookieSettings.pathAccessToken | default "/api" | quote }}
  CookieSettings__SameSiteRefreshToken: {{ .Values.cookieSettings.sameSiteRefreshToken | default "Strict" | quote }}
  CookieSettings__PathRefreshToken: {{ .Values.cookieSettings.pathRefreshToken | default "/api/auth/refresh" | quote }}
