apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "artsy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "artsy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "artsy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "artsy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "artsy.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "artsy.fullname" . }}-config
            - secretRef:
                name: artsy-secrets

          ports:
            - name: backend
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}